# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.athensworks.com
title: Athensworks
subtitle: "A coworking community in Athens, Ohio"
logo: /assets/athensworks_logo.gif
author: Athensworks
simple_search: https://www.google.com/search
description:

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

gems:
  - jekyll-redirect-from
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock


# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
permalink: /blog/:year/:month/:day/:title/
category_dir: blog/categories

paginate: 10          # Posts per page on the blog index
paginate_path: "posts/:num"  # Directory base for pagination URLs eg. /posts/2/
recent_posts: 0       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/github.html, asides/googleplus.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: athensworks
github_repo_count: 6
github_show_profile_link: true
github_skip_forks: false

# Twitter
twitter_user: athenwsworks
twitter_tweet_button: true

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name:
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id:

# Facebook Like
facebook_like: true
facebook_sidbar_embed: true
facebook_sidbar_page_url: http://www.facebook.com/Athensworks
facebook_sidebar_width: 250
facebook_sidebar_show_faces: true
facebook_sidebar_show_stream: false
facebook_sidebar_show_header: true


# Oscailte Theme Settings
gravatar: false
oscailte:
    hire: # The "Available for Hire" widget
        visible:
            footer: false
            sidebar: false
        footer-cols: 6 # Number of columns available for the footer component, max 12
        available: false # Whether or not you're available for hire
        vibrant: false # Makes the widget much more noticeable
        message: "Available for new opportunities"
    social:
        visible: true
        title: # Defaults to "Follow me!" if not present
        adn: # App.net
        coinbase:
        dribbble:
        facebook:
            user: Athensworks
            app_id: # For enabling Open Graph metadata
        github:
            user: Athensworks
            show_profile_link: true
        googleplus:
        hackernews:
        keybase:
        linkedin:
        pinterest:
        reddit:
        stackoverflow:
        twitter:
            user: athensworks
            widget: # Shows the Recent Tweets widget in sidebar
                is_shown:
                show_profile_link:
                widget_id:
        youtube:

theme: jekyll-theme-slate